### ISSUE TITLE
Sa

### ISSUE THREAD

**Issue by Fyxer** [AktilaCengiz/Discord-Bot-Gelistirme-Gunlukleri#6]
![Başlıksız-1SSS](https://user-images.githubusercontent.com/64753706/81169423-814c7680-8fa1-11ea-9a3b-7b76d39783c1.jpg)

**Comment by AktilaCengiz** [comment]
Aleyküm selam bu kısım sohbet için değil sadece hataları belirtmek için kullanınız.
